import { StyleSheet } from 'react-native';
import { Color, FontSize, FontWeight, Radius, Spacing } from '@/utils/Theme';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: Color.overlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    maxHeight: '80%',
    backgroundColor: Color.surface,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.xl,
  },
  handle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: Color.border,
    marginBottom: Spacing.md,
  },
  title: { fontSize: FontSize.lg, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  subtitle: { marginTop: 2, marginBottom: Spacing.md, fontSize: FontSize.sm, color: Color.textSecondary },

  inputRow: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'center' },
  inputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    height: 44,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Color.border,
    backgroundColor: Color.background,
  },
  input: { flex: 1, fontSize: FontSize.sm, color: Color.textPrimary },
  applyBtn: {
    paddingHorizontal: 18,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 76,
  },
  applyBtnText: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.primary },
  error: { marginTop: 6, fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.error },

  sectionLabel: {
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: Color.textPrimary,
  },
  loading: { marginVertical: Spacing.lg },
  empty: { fontSize: FontSize.sm, color: Color.textSecondary, paddingVertical: Spacing.md },
  list: {},

  card: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Color.border,
    backgroundColor: Color.surface,
  },
  cardDisabled: { opacity: 0.55 },
  cardIcon: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardBody: { flex: 1, minWidth: 0 },
  cardCode: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.extrabold,
    letterSpacing: 0.4,
    color: Color.textPrimary,
  },
  cardDiscount: { marginTop: 1, fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.primary },
  cardDesc: { marginTop: 2, fontSize: FontSize.xs, color: Color.textSecondary },
  cardHint: { marginTop: 4, fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.warning },

  tapApply: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: Radius.pill,
    backgroundColor: Color.primarySoft,
  },
  tapApplyDisabled: { backgroundColor: Color.background },
  tapApplyText: { fontSize: FontSize.xs, fontWeight: FontWeight.bold, color: Color.primary },
  tapApplyTextDisabled: { color: Color.placeholder },
});
