import { StyleSheet } from 'react-native';
import { Color, FontSize, FontWeight, Radius, Spacing } from '@/utils/Theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Color.background },
  content: { padding: Spacing.lg, paddingBottom: 140, gap: Spacing.md },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },

  sectionTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: Color.textPrimary,
    marginTop: Spacing.xs,
  },

  card: {
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
    paddingHorizontal: Spacing.md,
  },

  bizRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImg: { width: '100%', height: '100%' },
  bizInfo: { flex: 1, minWidth: 0 },
  bizName: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Color.textPrimary },
  bizMeta: { marginTop: 2, fontSize: FontSize.xs, color: Color.textSecondary },
  divider: { height: 1, backgroundColor: Color.border },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  rowLast: { borderBottomWidth: 0 },
  rowLabel: { fontSize: FontSize.sm, color: Color.textSecondary },
  rowValue: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Color.textPrimary },

  discountLabel: { fontSize: FontSize.sm, color: Color.success, fontWeight: FontWeight.semibold },
  discountValue: { fontSize: FontSize.sm, color: Color.success, fontWeight: FontWeight.bold },
  totalLabel: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Color.textPrimary },
  totalValue: { fontSize: FontSize.lg, fontWeight: FontWeight.extrabold, color: Color.textPrimary },

  addressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
  },
  addressIcon: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressInfo: { flex: 1, minWidth: 0 },
  addressLine: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Color.textPrimary },
  addressPlaceholder: { fontSize: FontSize.sm, color: Color.error, fontWeight: FontWeight.semibold },
  addressChange: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.primary },

  sheetOverlay: {
    flex: 1,
    backgroundColor: Color.overlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    maxHeight: '85%',
    backgroundColor: Color.surface,
    borderTopLeftRadius: Radius.lg,
    borderTopRightRadius: Radius.lg,
    paddingTop: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.xl,
  },
  sheetTitle: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.bold,
    color: Color.textPrimary,
    marginBottom: Spacing.sm,
  },
  addressScrollArea: {
    maxHeight: 420,
  },
  addressOption: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  addressLabel: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Color.primary,
    marginBottom: 2,
  },
  addressRadio: {
    width: 20,
    height: 20,
    marginTop: 2,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: Color.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressRadioSelected: { borderColor: Color.primary },
  addressRadioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: Color.primary },
  addNewAddressBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: Spacing.md,
    paddingVertical: 14,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Color.primary,
    borderStyle: 'dashed',
  },
  addNewAddressBtnText: { color: Color.primary, fontSize: FontSize.md, fontWeight: FontWeight.bold },

  bar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    paddingBottom: Spacing.xl,
    backgroundColor: Color.surface,
    borderTopWidth: 1,
    borderTopColor: Color.border,
  },
  barLabel: { fontSize: FontSize.xs, color: Color.textSecondary, fontWeight: FontWeight.semibold },
  barTotal: { fontSize: FontSize.lg, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  continueBtn: { minWidth: 170 },
});
