import { StyleSheet } from 'react-native';
import { Color, FontSize, FontWeight, Radius, Spacing } from '@/utils/Theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Color.background },
  content: { padding: Spacing.lg, paddingBottom: Spacing.xl, gap: Spacing.md },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.xl },
  notFound: { fontSize: FontSize.md, color: Color.textSecondary },

  summary: {
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.lg,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: Radius.lg,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImg: { width: '100%', height: '100%' },
  bizName: { fontSize: FontSize.xl, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  chipRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, flexWrap: 'wrap', justifyContent: 'center' },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Radius.pill,
    backgroundColor: Color.primarySoft,
  },
  chipText: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.primaryDark },
  statusPill: { paddingHorizontal: 12, paddingVertical: 5, borderRadius: Radius.pill },
  statusText: { fontSize: FontSize.xs, fontWeight: FontWeight.bold },
  placed: { fontSize: FontSize.xs, color: Color.textSecondary },

  sectionTitle: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.textPrimary },

  card: {
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
    paddingHorizontal: Spacing.md,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  itemThumb: {
    width: 44,
    height: 44,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  itemThumbImg: { width: '100%', height: '100%' },
  itemMain: { flex: 1, minWidth: 0 },
  itemName: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Color.textPrimary },
  itemMeta: { marginTop: 2, fontSize: FontSize.xs, color: Color.textSecondary },
  itemPrice: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.textPrimary },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  rowLast: { borderBottomWidth: 0 },
  rowLabel: { fontSize: FontSize.sm, color: Color.textSecondary },
  rowValue: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Color.textPrimary },
  priceValue: { fontSize: FontSize.md, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  due: { color: Color.warning, fontWeight: FontWeight.extrabold },

  note: { paddingVertical: Spacing.md, fontSize: FontSize.sm, color: Color.textPrimary, lineHeight: FontSize.sm * 1.4 },

  cancelBtn: {
    marginTop: Spacing.sm,
    paddingVertical: 14,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Color.error,
    backgroundColor: Color.errorSoft,
    alignItems: 'center',
  },
  cancelText: { color: Color.error, fontSize: FontSize.md, fontWeight: FontWeight.bold },
});
