import { StyleSheet } from 'react-native';
import { Color, FontSize, FontWeight, Radius, Spacing } from '@/utils/Theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Color.background,
  },
  content: {
    padding: Spacing.lg,
  },

  // Store header
  storeHead: {
    flexDirection: 'row',
    gap: Spacing.md,
    alignItems: 'center',
    padding: Spacing.md,
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
    marginBottom: Spacing.lg,
  },
  storeIcon: {
    width: 56,
    height: 56,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeInfo: { flex: 1, minWidth: 0 },
  storeName: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extrabold,
    color: Color.textPrimary,
  },
  storeMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: 6,
    flexWrap: 'wrap',
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: Radius.pill,
    backgroundColor: Color.primarySoft,
  },
  chipText: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.primaryDark },
  rating: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  ratingText: { fontSize: FontSize.xs, color: Color.textSecondary, fontWeight: FontWeight.semibold },

  sectionTitle: {
    fontSize: FontSize.md,
    fontWeight: FontWeight.bold,
    color: Color.textPrimary,
    marginBottom: Spacing.sm,
  },

  // Contact card
  contactCard: {
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.lg,
  },
  contactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Color.border,
  },
  contactRowLast: { borderBottomWidth: 0 },
  contactIcon: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactText: { flex: 1, minWidth: 0 },
  contactLabel: { fontSize: FontSize.xs, color: Color.textSecondary },
  contactValue: { marginTop: 2, fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Color.textPrimary },
  callAction: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.primary },

  empty: { alignItems: 'center', gap: Spacing.sm, paddingVertical: Spacing.xl },
  emptyText: { fontSize: FontSize.sm, color: Color.textSecondary, textAlign: 'center' },

  viewAll: {
    marginTop: Spacing.sm,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semibold,
    color: Color.primary,
  },

  // ── Section group + e-commerce cards ─────────────────────────────────
  group: { marginTop: Spacing.lg },
  groupHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  groupTitle: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Color.textPrimary },
  groupCount: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Color.textSecondary,
    backgroundColor: Color.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 1,
    borderRadius: Radius.pill,
  },
  eRow: { gap: Spacing.md, paddingRight: Spacing.lg, paddingVertical: 2 },

  eCard: {
    width: 152,
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
    overflow: 'hidden',
  },
  eImageWrap: {
    height: 120,
    backgroundColor: Color.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eImage: { width: '100%', height: '100%' },
  eOutBadge: {
    position: 'absolute',
    top: Spacing.sm,
    left: Spacing.sm,
    backgroundColor: 'rgba(6,11,24,0.78)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: Radius.pill,
  },
  eOutText: { fontSize: 10, fontWeight: FontWeight.bold, color: Color.white },

  eBody: { padding: Spacing.sm, gap: 3 },
  eName: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.textPrimary, minHeight: 34 },
  ePrice: { fontSize: FontSize.md, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  eUnit: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.textSecondary },
  eStock: { fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.success },
  eStockOut: { color: Color.error },

  eAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 6,
    paddingVertical: 8,
    borderRadius: Radius.md,
    backgroundColor: Color.primary,
  },
  eAddText: { color: Color.white, fontSize: FontSize.sm, fontWeight: FontWeight.bold },
  eStepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
    borderWidth: 1,
    borderColor: Color.primary,
    borderRadius: Radius.md,
    overflow: 'hidden',
  },
  eStepBtn: {
    width: 40,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Color.primarySoft,
  },
  eQty: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.textPrimary },

  // Product card
  pCard: {
    flexDirection: 'row',
    gap: Spacing.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Color.surface,
    borderWidth: 1,
    borderColor: Color.border,
  },
  pMain: { flex: 1, minWidth: 0 },
  pName: { fontSize: FontSize.md, fontWeight: FontWeight.bold, color: Color.textPrimary },
  pDesc: { marginTop: 2, fontSize: FontSize.sm, color: Color.textSecondary },
  pPrice: { marginTop: 6, fontSize: FontSize.md, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  perUnit: { fontSize: FontSize.sm, fontWeight: FontWeight.semibold, color: Color.textSecondary },
  pStock: { marginTop: 2, fontSize: FontSize.xs, fontWeight: FontWeight.semibold, color: Color.success },
  pOut: { color: Color.error },

  pAction: { alignItems: 'center', justifyContent: 'center', gap: 4 },
  addBtn: {
    paddingHorizontal: Spacing.lg,
    paddingVertical: 8,
    borderRadius: Radius.md,
    backgroundColor: Color.primary,
  },
  addText: { color: Color.white, fontSize: FontSize.sm, fontWeight: FontWeight.bold },
  disabled: { opacity: 0.4 },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Color.primary,
    borderRadius: Radius.md,
    overflow: 'hidden',
  },
  stepBtn: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Color.primarySoft,
  },
  qty: {
    minWidth: 30,
    textAlign: 'center',
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: Color.textPrimary,
  },
  perUnitSmall: { fontSize: 10, color: Color.textSecondary },

  // Cart bar
  cartBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    backgroundColor: Color.surface,
    borderTopWidth: 1,
    borderTopColor: Color.border,
  },
  cartCount: { fontSize: FontSize.xs, color: Color.textSecondary, fontWeight: FontWeight.semibold },
  cartTotal: { fontSize: FontSize.lg, fontWeight: FontWeight.extrabold, color: Color.textPrimary },
  checkoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: Spacing.lg,
    paddingVertical: 14,
    borderRadius: Radius.md,
    backgroundColor: Color.primary,
  },
  checkoutText: { color: Color.white, fontSize: FontSize.md, fontWeight: FontWeight.bold },

  // Checkout sheet
  sheetOverlay: { flex: 1, backgroundColor: Color.overlay, justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: Color.surface,
    borderTopLeftRadius: Radius.lg,
    borderTopRightRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.sm,
  },
  sheetTitle: { fontSize: FontSize.lg, fontWeight: FontWeight.bold, color: Color.textPrimary },
  sheetSub: { fontSize: FontSize.sm, color: Color.textSecondary, marginBottom: Spacing.sm },
  payOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Color.border,
    backgroundColor: Color.surface,
  },
  payOptionActive: { borderColor: Color.primary, backgroundColor: Color.primarySoft },
  payText: { flex: 1, minWidth: 0 },
  payTitle: { fontSize: FontSize.sm, fontWeight: FontWeight.bold, color: Color.textPrimary },
  paySub: { marginTop: 2, fontSize: FontSize.xs, color: Color.textSecondary },
  sheetActions: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.md },
  sheetBtn: { flex: 1, paddingVertical: 14, borderRadius: Radius.md, alignItems: 'center' },
  sheetGhost: { backgroundColor: Color.surface, borderWidth: 1, borderColor: Color.border },
  sheetGhostText: { color: Color.textPrimary, fontSize: FontSize.md, fontWeight: FontWeight.semibold },
  sheetPrimary: { backgroundColor: Color.primary, flex: 2 },
  sheetPrimaryText: { color: Color.white, fontSize: FontSize.md, fontWeight: FontWeight.bold },
});
